### ISSUE TITLE
Start web not working 

### ISSUE THREAD

**Issue by xerxiastudios** [ritmillio/expo-router-starter-kit#19]
```
Web Bundling failed 488ms
Unable to resolve "react-hook-form" from "src\app\(auth)\sign-in.tsx"
```

Gettting this error on yarn web

**Comment by byoungdale** [comment]
I am having the same issue. Seems related to [this issue](https://github.com/expo/expo/issues/23322), except their suggestions did not work for me

**Comment by ritmillio** [comment]
This is solved thanks to @kewinzaq1. I close this issue for now.
