### ISSUE TITLE
Adding support to socketi

### ISSUE THREAD

**Issue by geoman2** [ritmillio/expo-router-starter-kit#27]
Hi, have you considered to add support to soketi, an open source messaging framework, a good alternative to oneSignal to deliver push messages? It's running on cloudflare but also on premise (railway has added support on their VMs/VPS).
Their twitter https://twitter.com/soketirealtime

**Comment by ritmillio** [comment]
Hi @geoman2 , what's the benefit using this soketi over OneSignal or Expo Push ?

**Comment by geoman2** [comment]
Maybe to run your own push server on top of cloudflare or even own server (farm of VPS)?

**Comment by ritmillio** [comment]
This soketi looks really interesting however this repository sole purpose is to boost development and certanly this would not help in regard of the initial project setup therfor for now this repo will stick with OneSignal. Thanks for suggesting tho, always interested in new tech.
