### ISSUE TITLE
3rd party libraries compatibility with expo-router

### ISSUE THREAD

**Issue by sgrund14** [ritmillio/expo-router-starter-kit#52]
hello

stumbled upon your repo looking for an answer to this question...

is flashlist incompatible with expo-router? his is the only place where I can find some evidence that it is! it's been breaking in my iOS simulator whenever I try to use it...

do you happen to know why exactly it isn't compatible?

**Comment by ritmillio** [comment]
Hello @sgrund14 ,

Unfortunaetlly I have no way to detect which 3rd party libraries are working or not working with expo-router. Important to know that expo-router is still considered to be an experiment and not every library is supported. Even Expo Go is not supported and when it's enabled like on this template or any other example with router these issues are not seen until you complie/build to iOS and/or Android. This caused me a headache as well so I would recommende to stick with the original Expo way until all the packages or at least most of them will receive support.. until then I would use expo-router as a test-build/experiment.

**Comment by sgrund14** [comment]
ah, I see thanks! i was just going off your note here in the read me:

![Screenshot 2024-01-19 at 4 05 19 PM](https://github.com/justlaunch-app/expo-router-starter-kit/assets/14083701/97a51944-b544-481d-887d-2591cc8ab12e)
